name: JMeter Load Test

on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Number of threads (users)'
        required: true
        default: '10'

jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    
    # Step 3: Install JMeter
    - name: Install JMeter
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openjdk-11-jdk
        wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        export JMETER_HOME=$(pwd)/apache-jmeter-5.6.3
        export PATH=$JMETER_HOME/bin:$PATH
    
    # Step 4: Run the JMeter test with the specified number of threads
    - name: Run JMeter Load Test
      run: |
        $JMETER_HOME/bin/jmeter -n -t LoadTestBlazeDemo-${{ github.event.inputs.threads }}-users.jmx -l results.jtl -e -o reports/${{ github.event.inputs.threads }}-users

    # Step 5: Upload the results as an artifact
    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-reports-${{ github.event.inputs.threads }}-users
        path: reports/${{ github.event.inputs.threads }}-users

    # Step 6: Upload JTL results as an artifact (optional for raw results)
    - name: Upload JTL Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-jtl-results
        path: results.jtl
